# config.yaml
name: "temperature_swinir_x2"

model:
  pretrained_path: "/path/to/001_classicalSR_DIV2K_s48w8_SwinIR-M_x2.pth"
  scale_factor: 2
  freeze_backbone: false  # Set to true to only train adapters

data:
  data_dir: "/pscratch/sd/s/stodi/climate-new/sample_chirps"
  num_train_files: 33
  scale_factor: 0.001  # Temperature scale factor
  colormap: "turbo"
  patch_size: 128  # Not used when patch_height/width are specified
  patch_height: 800  # Rectangular patch height
  patch_width: 200   # Rectangular patch width

training:
  epochs: 100
  batch_size: 4
  lr: 0.0002
  lr_min: 0.000001
  weight_decay: 0.01
  grad_clip: 1.0

  save_dir: "./experiments"
  save_interval: 10
  log_interval: 50
  num_val_images: 5

  resume: null  # Path to checkpoint to resume from

# Validation settings
validation:
  batch_size: 1
  full_image: true  # Validate on full images
  max_images: 10    # Maximum validation images to use